"""Add website review support

Revision ID: 3a0289928e9c
Revises: 6bee9faef024
Create Date: 2025-08-18 09:34:31.023913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a0289928e9c'
down_revision: Union[str, None] = '6bee9faef024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('analyses', sa.Column('analysis_type', sa.String(), nullable=False))
    op.alter_column('analyses', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('analyses', 'platform',
               existing_type=postgresql.ENUM('google_play', 'app_store', name='platform'),
               nullable=True)
    op.create_index(op.f('ix_analyses_website_url'), 'analyses', ['website_url'], unique=False)
    op.add_column('reviews', sa.Column('website_url', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('source_platform', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('author', sa.String(), nullable=True))
    op.alter_column('reviews', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_reviews_website_url'), 'reviews', ['website_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_website_url'), table_name='reviews')
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('reviews', 'author')
    op.drop_column('reviews', 'source_platform')
    op.drop_column('reviews', 'website_url')
    op.drop_index(op.f('ix_analyses_website_url'), table_name='analyses')
    op.alter_column('analyses', 'platform',
               existing_type=postgresql.ENUM('google_play', 'app_store', name='platform'),
               nullable=False)
    op.alter_column('analyses', 'app_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('analyses', 'analysis_type')
    op.drop_column('analyses', 'website_url')
    # ### end Alembic commands ###
