"""add_progress_tracking_to_analysis

Revision ID: 802ccd5fa22f
Revises: 3a0289928e9c
Create Date: 2025-08-21 10:29:57.449245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802ccd5fa22f'
down_revision: Union[str, None] = '3a0289928e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('progress', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('analyses', sa.Column('status_message', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('task_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'task_id')
    op.drop_column('analyses', 'status_message')
    op.drop_column('analyses', 'progress')
    # ### end Alembic commands ###
